### PR TITLE
Lecture 3 Part 1

### PR DESCRIPTION
**Pull request by nivedk**

### CODE REVIEW

**Comment by nivedk** [comment]
A general observation. It's best to avoid having 2 people working on the same Jupyter notebook at one time. This is because every time we run a notebook, many small changes are made, especially in the json scripts leading to a lot of merge conflicts. Moreover, resolving merge conflicts also becomes difficult because the Notebook itself gets corrupted due to the conflicts, so we cannot open it.

**Comment by AthletiCoder** [comment]
> A general observation. It's best to avoid having 2 people working on the same Jupyter notebook at one time. 

Ok, I thought maybe we can separate the sections beforehand. But if that doesn't work, we'll work on separate files.

**Comment by AthletiCoder** [comment]
@nivedk what about this one?

**Review by nivedk — COMMENTED** [review]
Seems good

**Review by nivedk — COMMENTED** [review]
.

**Pull request merged**
